- name: 'default'
  host: localhost
  port: 9000
  discovery_path:
  use_https: False
  taxii_version: '1.1'
  headers:
  auth:
    username:
    password:
    cacert_path:
    cert_file:
    key_file:
    key_password:
    jwt_auth_url:
    verify_ssl: True
  collections:
    - collection